CRITICAL - 2022-02-05 21:08:48 --> Invalid file: welcome_hayup.php
#0 C:\xampp\htdocs\code4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('welcome_hayup.p...')
#1 C:\xampp\htdocs\code4\system\Common.php(1089): CodeIgniter\View\View->render('welcome_hayup', Array, true)
#2 C:\xampp\htdocs\code4\app\Controllers\Home.php(9): view('welcome_hayup')
#3 C:\xampp\htdocs\code4\system\CodeIgniter.php(825): App\Controllers\Home->index()
#4 C:\xampp\htdocs\code4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\code4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\code4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-02-05 21:09:16 --> Invalid file: tanginamo_message.php
#0 C:\xampp\htdocs\code4\system\View\View.php(198): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('tanginamo_messa...')
#1 C:\xampp\htdocs\code4\system\Common.php(1089): CodeIgniter\View\View->render('tanginamo_messa...', Array, true)
#2 C:\xampp\htdocs\code4\app\Controllers\Home.php(9): view('tanginamo_messa...')
#3 C:\xampp\htdocs\code4\system\CodeIgniter.php(825): App\Controllers\Home->index()
#4 C:\xampp\htdocs\code4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#5 C:\xampp\htdocs\code4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\code4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
ERROR - 2022-02-05 21:10:47 --> Error connecting to the database: Unknown database 'logins'
CRITICAL - 2022-02-05 21:28:37 --> Class 'App\Controllers\BaseController' not found
#0 C:\xampp\htdocs\code4\system\Autoloader\Autoloader.php(264): include_once()
#1 C:\xampp\htdocs\code4\system\Autoloader\Autoloader.php(241): CodeIgniter\Autoloader\Autoloader->includeFile('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\code4\system\Autoloader\Autoloader.php(219): CodeIgniter\Autoloader\Autoloader->loadInNamespace('App\\Controllers...')
#3 [internal function]: CodeIgniter\Autoloader\Autoloader->loadClass('App\\Controllers...')
#4 [internal function]: spl_autoload_call('App\\Controllers...')
#5 C:\xampp\htdocs\code4\system\CodeIgniter.php(790): class_exists('\\App\\Controller...', true)
#6 C:\xampp\htdocs\code4\system\CodeIgniter.php(399): CodeIgniter\CodeIgniter->startController()
#7 C:\xampp\htdocs\code4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\code4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-02-05 21:39:22 --> Class 'App\Models\UserModel' not found
#0 C:\xampp\htdocs\code4\system\CodeIgniter.php(825): App\Controllers\SigninController->loginAuth()
#1 C:\xampp\htdocs\code4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SigninController))
#2 C:\xampp\htdocs\code4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\code4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\code4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-02-05 23:06:36 --> Class 'App\Models\UserModel' not found
#0 C:\xampp\htdocs\code4\system\CodeIgniter.php(825): App\Controllers\SigninController->loginAuth()
#1 C:\xampp\htdocs\code4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SigninController))
#2 C:\xampp\htdocs\code4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\code4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\code4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-02-05 23:06:41 --> Class 'App\Models\UserModel' not found
#0 C:\xampp\htdocs\code4\system\CodeIgniter.php(825): App\Controllers\SigninController->loginAuth()
#1 C:\xampp\htdocs\code4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SigninController))
#2 C:\xampp\htdocs\code4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\code4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\code4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2022-02-05 23:07:06 --> Class 'App\Models\UserModel' not found
#0 C:\xampp\htdocs\code4\system\CodeIgniter.php(825): App\Controllers\SigninController->loginAuth()
#1 C:\xampp\htdocs\code4\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\SigninController))
#2 C:\xampp\htdocs\code4\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\code4\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\code4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
